### PR TITLE
Save form data

### PR DESCRIPTION
**Pull request by yosefHesham**
**Brief of what changed**
Used local storage to save form data to meet a good user experience.

---
**Changes Made:**

- Store form data into an object initially
- Fetch saved data if exists
- Add input event listener to keep track of what user types.
- Save the entered data

### CODE REVIEW

**Review by nicupop729 — CHANGES_REQUESTED** [review]
# STATUS: Required Changes ♻️

Hi @yosefHesham, 

Good job!
Congratulations on implementing these milestone requirements!



### Some highlights for you
* Correct GitHub flow practice ✔️ 
* Good commit messages ✔️ 
* Clean codebase ✔️ 


### Required Changes ♻️

While you have done well in this project, you missed a crucial aspect: **collaborating!**
Very well that you did it by yourself, but collaborating brings a lot of advantages. 
We learn from each other a lot, and while you knew how to handle this milestone, your partners could learn from you. As well, it gives you and your partners the fabulous opportunity to develop your soft skills!

- [ ] As it is a project requirement, kindly, bring your partners together and explain to them how you have done your project and ask them to bring improvements and commits to this milestone as well!

Cheers and Happy **COLLABORATING!** 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by yosefHesham** [comment]
@nicupop729 I will explain for sure, but the point is about committing 😅
I hope we find something to add .

**Review by roshan-bajgain — CHANGES_REQUESTED** [review]
Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight :tada: :champagne: 
- Nice PR description and title :+1: 
- Nice README file :heavy_check_mark:
- No linter error :heavy_check_mark:
- GitHub flow is followed :+1:


## Required Changes ♻️
- [ ]   As the previous, reviewer said **kindly, bring your partners together and explain to them how you have done your project and ask them to bring improvements and commit to this milestone as well!** But when I check your commit message then I didn't find your partner commit so kindly follow the instruction said by the previous reviewer.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by yosefHesham** [comment]
@roshan-bajgain  have you read what I wrote in the additional info!!?!

**Comment by roshan-bajgain** [comment]
@yosefHesham Kindly add more description in your README file and tell your partner to commit to this. Thank you

**Review by RolandM99 — APPROVED** [review]
<h1>Status: Approve 🥇 ✔</h1>

### Hello team 🤝  , 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy codding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
